# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arthur/semesterproject/depth-camera-automatic-calibration

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arthur/semesterproject/depth-camera-automatic-calibration

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arthur/semesterproject/depth-camera-automatic-calibration/CMakeFiles /home/arthur/semesterproject/depth-camera-automatic-calibration/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arthur/semesterproject/depth-camera-automatic-calibration/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin/computecalibration

# Build rule for target.
bin/computecalibration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/computecalibration
.PHONY : bin/computecalibration

# fast build rule for target.
bin/computecalibration/fast:
	$(MAKE) -f CMakeFiles/bin/computecalibration.dir/build.make CMakeFiles/bin/computecalibration.dir/build
.PHONY : bin/computecalibration/fast

src/computecalibration.o: src/computecalibration.cpp.o
.PHONY : src/computecalibration.o

# target to build an object file
src/computecalibration.cpp.o:
	$(MAKE) -f CMakeFiles/bin/computecalibration.dir/build.make CMakeFiles/bin/computecalibration.dir/src/computecalibration.cpp.o
.PHONY : src/computecalibration.cpp.o

src/computecalibration.i: src/computecalibration.cpp.i
.PHONY : src/computecalibration.i

# target to preprocess a source file
src/computecalibration.cpp.i:
	$(MAKE) -f CMakeFiles/bin/computecalibration.dir/build.make CMakeFiles/bin/computecalibration.dir/src/computecalibration.cpp.i
.PHONY : src/computecalibration.cpp.i

src/computecalibration.s: src/computecalibration.cpp.s
.PHONY : src/computecalibration.s

# target to generate assembly for a file
src/computecalibration.cpp.s:
	$(MAKE) -f CMakeFiles/bin/computecalibration.dir/build.make CMakeFiles/bin/computecalibration.dir/src/computecalibration.cpp.s
.PHONY : src/computecalibration.cpp.s

src/gridcalibration.o: src/gridcalibration.cpp.o
.PHONY : src/gridcalibration.o

# target to build an object file
src/gridcalibration.cpp.o:
	$(MAKE) -f CMakeFiles/bin/computecalibration.dir/build.make CMakeFiles/bin/computecalibration.dir/src/gridcalibration.cpp.o
.PHONY : src/gridcalibration.cpp.o

src/gridcalibration.i: src/gridcalibration.cpp.i
.PHONY : src/gridcalibration.i

# target to preprocess a source file
src/gridcalibration.cpp.i:
	$(MAKE) -f CMakeFiles/bin/computecalibration.dir/build.make CMakeFiles/bin/computecalibration.dir/src/gridcalibration.cpp.i
.PHONY : src/gridcalibration.cpp.i

src/gridcalibration.s: src/gridcalibration.cpp.s
.PHONY : src/gridcalibration.s

# target to generate assembly for a file
src/gridcalibration.cpp.s:
	$(MAKE) -f CMakeFiles/bin/computecalibration.dir/build.make CMakeFiles/bin/computecalibration.dir/src/gridcalibration.cpp.s
.PHONY : src/gridcalibration.cpp.s

src/tracking.o: src/tracking.cpp.o
.PHONY : src/tracking.o

# target to build an object file
src/tracking.cpp.o:
	$(MAKE) -f CMakeFiles/bin/computecalibration.dir/build.make CMakeFiles/bin/computecalibration.dir/src/tracking.cpp.o
.PHONY : src/tracking.cpp.o

src/tracking.i: src/tracking.cpp.i
.PHONY : src/tracking.i

# target to preprocess a source file
src/tracking.cpp.i:
	$(MAKE) -f CMakeFiles/bin/computecalibration.dir/build.make CMakeFiles/bin/computecalibration.dir/src/tracking.cpp.i
.PHONY : src/tracking.cpp.i

src/tracking.s: src/tracking.cpp.s
.PHONY : src/tracking.s

# target to generate assembly for a file
src/tracking.cpp.s:
	$(MAKE) -f CMakeFiles/bin/computecalibration.dir/build.make CMakeFiles/bin/computecalibration.dir/src/tracking.cpp.s
.PHONY : src/tracking.cpp.s

src/undistort.o: src/undistort.cpp.o
.PHONY : src/undistort.o

# target to build an object file
src/undistort.cpp.o:
	$(MAKE) -f CMakeFiles/bin/computecalibration.dir/build.make CMakeFiles/bin/computecalibration.dir/src/undistort.cpp.o
.PHONY : src/undistort.cpp.o

src/undistort.i: src/undistort.cpp.i
.PHONY : src/undistort.i

# target to preprocess a source file
src/undistort.cpp.i:
	$(MAKE) -f CMakeFiles/bin/computecalibration.dir/build.make CMakeFiles/bin/computecalibration.dir/src/undistort.cpp.i
.PHONY : src/undistort.cpp.i

src/undistort.s: src/undistort.cpp.s
.PHONY : src/undistort.s

# target to generate assembly for a file
src/undistort.cpp.s:
	$(MAKE) -f CMakeFiles/bin/computecalibration.dir/build.make CMakeFiles/bin/computecalibration.dir/src/undistort.cpp.s
.PHONY : src/undistort.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bin/computecalibration"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/computecalibration.o"
	@echo "... src/computecalibration.i"
	@echo "... src/computecalibration.s"
	@echo "... src/gridcalibration.o"
	@echo "... src/gridcalibration.i"
	@echo "... src/gridcalibration.s"
	@echo "... src/tracking.o"
	@echo "... src/tracking.i"
	@echo "... src/tracking.s"
	@echo "... src/undistort.o"
	@echo "... src/undistort.i"
	@echo "... src/undistort.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

